[BrokenLinksH2] Fix path in link
Azure/azure-docs-sdk-dotnet pull request #2158
Opened 2022-04-05 14:20 UTC by DhurataJ

Broken images are not in repo. Removing broken images from line 36 and 40.

2022-04-05 21:03 UTC, tfosmark commented on api/overview/azure/microsoft.azure.webjobs.extensions.signalrservice-readme.md
> +    [SignalR Service mode setting]
@DhurataJ You can remove this text as well, since you removed the image.

2022-04-05 21:04 UTC, tfosmark requested changes
Line 40 - delete the whole line :-)

2022-04-06 06:28 UTC, tfosmark commented
**Global effort to fix broken links**

@Taojunshen 

The Aquent team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please merge this PR. Thanks!

2022-04-06 06:29 UTC, tfosmark approved these changes

2022-04-06 18:12 UTC, tfosmark approved these changes

2022-04-07 18:00 UTC, jsquire commented
Hi @DhurataJ.    Please be aware that this file is generated by an export process in the Azure SDK repository.   Changes here will be overwritten the next time the package is published.  The source for this content is [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/README.md); for this fix to stick across releases, we'd need to make the change there.

2022-04-07 18:09 UTC, jsquire approved these changes

2022-04-07 18:09 UTC, jsquire commented on api/overview/azure/microsoft.azure.webjobs.extensions.signalrservice-readme.md
> +    [Deploy to Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3a%2f%2fraw.githubusercontent.com%2fAzure%2fazure-quickstart-templates%2fmaster%2fquickstarts%2fmicrosoft.signalrse
```suggestion
[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3a%2f%2fraw.githubusercontent.com%2fAzure%2fazure-quickstart-templates%2fmaster%2fquickstarts%2fmicrosoft.signalrservice%2fsignalr%2fazuredeploy.json)
```

2022-04-08 14:18 UTC, jsquire approved these changes

2022-04-08 14:18 UTC, merged

2022-04-08 19:45 UTC, jsquire commented
Source updated by [#28114](https://github.com/Azure/azure-sdk-for-net/pull/28114).