add authentication part and add new sdk sample
Azure/azure-docs-sdk-dotnet pull request #2211
Opened 2022-08-02 03:40 UTC by xboxeer

Fix issue: https://github.com/Azure/azure-sdk-for-net/issues/29901

2022-08-02 19:11 UTC, scottaddie commented
@xboxeer I'd suggest updating the code sample in the source code repo instead. If a new version of the Track 1 library is ever released, these docs changes will be overwritten. @danieljurek, Do you agree?

2022-08-02 20:28 UTC, scottaddie commented
Disregard my concern regarding overwriting. I've discussed with Daniel. Reviewing the PR now.

2022-08-02 22:04 UTC, scottaddie requested changes

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +PublicIPAddressCollection publicIps=resourceGroup.GetPublicIPAddresses();
```suggestion
VirtualMachineCollection vms = resourceGroup.GetVirtualMachines();
NetworkInterfaceCollection nics = resourceGroup.GetNetworkInterfaces();
VirtualNetworkCollection vns = resourceGroup.GetVirtualNetworks();
PublicIPAddressCollection publicIps = resourceGroup.GetPublicIPAddresses();
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +        Subnets=
```suggestion
        Location = AzureLocation.WestUS,
        Subnets =
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +            Name="testSubNet",
```suggestion
            Name = "testSubNet",
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +    },
```suggestion
        {
            "10.0.0.0/16"
        },
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +        IPConfigurations={
```suggestion
        Location = AzureLocation.WestUS,
        IPConfigurations = {
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +                Version="latest"
```suggestion
        HardwareProfile = new VirtualMachineHardwareProfile()
        {
            VmSize = VirtualMachineSizeType.BasicA0
        },
        OSProfile = new VirtualMachineOSProfile()
        {
            ComputerName = computeName,
            AdminUsername = admin,
            AdminPassword = pwd,
            LinuxConfiguration = new LinuxConfiguration()
            {
                DisablePasswordAuthentication = false,
                ProvisionVmAgent = true
            }
        },
        StorageProfile = new VirtualMachineStorageProfile()
        {
            OSDisk = new VirtualMachineOSDisk(DiskCreateOptionType.FromImage),
            ImageReference = new ImageReference()
            {
                Offer = "UbuntuServer",
                Publisher = "Canonical",
                Sku = "18.04-LTS",
                Version = "latest"
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +        NetworkProfile=new VirtualMachineNetworkProfile()
```suggestion
        NetworkProfile = new VirtualMachineNetworkProfile()
```

2022-08-02 22:04 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +        }
```suggestion
            NetworkInterfaces =
            {
                new VirtualMachineNetworkInterfaceReference()
                {
                    Id = nicResource.Id
                }
            }
```

2022-08-03 15:00 UTC, xboxeer commented
@scottaddie updated according to your suggestion

2022-08-04 00:56 UTC, scottaddie approved these changes
Here are some suggestions to consider, and then this PR looks good.

2022-08-04 00:56 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +    },
```suggestion
        {
            new SubnetData()
            {
                Name = "testSubNet",
                AddressPrefix = "10.0.0.0/24"
            }
        },
```

2022-08-04 00:56 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +
Remove blank line
```suggestion
```

2022-08-04 00:56 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +    }
Fix indentation
```suggestion
            new NetworkInterfaceIPConfigurationData()
            {
                Name = "Primary",
                Primary = true,
                Subnet = new SubnetData() { Id = vnetResrouce?.Data.Subnets.First().Id },
                PrivateIPAllocationMethod = NetworkIPAllocationMethod.Dynamic,
                PublicIPAddress = new PublicIPAddressData() { Id = ipResource?.Data.Id }
            }
        }
```

2022-08-04 00:56 UTC, scottaddie commented on api/overview/azure/virtualmachines.md
> +        IPConfigurations = {
```suggestion
        IPConfigurations =
        {
```

2022-08-04 02:17 UTC, merged